name: 'Slack notify with mention string'
description: 'Send the notification to slack with mention string'
author: 'Taichi Araki, Sansan Inc.'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  webhookURL:
    description: 'Slackにメッセージを送るためのWebHookURL'
    required: true
    default: ''
  mentionString:
    description: 'Slackのメンション文字列'
    required: true
    default: ''
  messageTemplate:
    description: 'Slackメッセージのテンプレート'
    required: true
    default: ''
runs:
  using: node20
  main: dist/index.js
